export const SEO_META = {
  pricing: {
    title: "Edooqoo Pricing — Free, Side-Gig & Full-Time Plans",
    description:
      "Edooqoo pricing: Free, Side-Gig ($9/mo), Full-Time (from $19/mo). All plans include 29 exercise types for CEFR A1-C2 English teaching.",
    path: "/pricing",
  },
  about: {
    title: "About Edooqoo — Built by English Teachers, for Teachers",
    description:
      "Edooqoo helps English teachers create personalized worksheets, assign AI-graded homework, and track CEFR A1-C2 progress with 29 exercise types.",
    path: "/about",
  },
  blog: {
    title: "Edooqoo Blog — Teaching Tips for English Tutors",
    description:
      "Articles for English teachers: AI teaching tips, worksheet creation guides, classroom management, CEFR assessment strategies.",
    path: "/blog",
  },
  glossary: {
    title: "ESL/EFL Glossary — Edooqoo Teaching Terms",
    description:
      "Glossary of ELT terms including CEFR, ESL, spaced repetition, andragogy. Learn how Edooqoo supports these English teaching concepts.",
    path: "/glossary",
  },
  exerciseTypes: {
    title: "29 Exercise Types for English Teachers — Edooqoo",
    description:
      "Guide to all 29 Edooqoo exercise types: 20 basic, 5 audio, 4 picture. Each with CEFR levels and ESL/EFL use cases.",
    path: "/exercise-types",
  },
  eslWorksheets: {
    title: "ESL Worksheets — AI-Generated for Adult Learners",
    description:
      "Generate personalized ESL worksheets in 60 seconds. 29 exercise types, CEFR A1-C2, business English, IELTS prep. Free to start.",
    path: "/esl-worksheets",
  },
  englishGamesForLearners: {
    title: "English Games for Learners — 12 Adult-Friendly Ideas",
    description:
      "12 classroom games for adult English learners: vocabulary, grammar, speaking. Print-ready worksheets generated by AI in 60 seconds.",
    path: "/blog/english-games-for-learners",
  },
  eslGamesForTeachers: {
    title: "ESL Games for Teachers — 15 Tested Activities",
    description:
      "15 ESL games tested by Martha (10 yrs ESL). Speaking, grammar, vocab — each game pairs with an AI-generated Edooqoo worksheet.",
    path: "/blog/esl-games-for-teachers",
  },
  teachEnglishOnlineGuide: {
    title: "How to Teach English Online — Complete 2026 Guide",
    description:
      "Start teaching English online: pricing, tools, lesson prep, student acquisition. Tutor toolkit with AI worksheets and homework grading.",
    path: "/blog/teach-english-online-guide",
  },
  forEnglishTutors: {
    title: "English Tutor Tools — Run a Pro Tutoring Business",
    description:
      "Tools for English tutors: AI worksheet generator, automated homework grading, student progress tracking, calendar with payments.",
    path: "/for-english-tutors",
  },
  eslClassToolkit: {
    title: "ESL Class Toolkit — Materials, Plans, Activities",
    description:
      "Complete ESL class toolkit: lesson plan templates, worksheet generator, placement test, flashcards. For 1-on-1 and small group classes.",
    path: "/resources/esl-class-toolkit",
  },
} as const;