/**
 * useWelcomeTestHistory — v6.2
 *
 * Returns the chronological list of Welcome Test attempts for a (student, teacher)
 * pair, each joined with its corresponding `student_learning_profiles` row by
 * `welcome_test_id`. Used by `WelcomeTestComparisonView` to render side-by-side
 * deltas between attempts.
 *
 * Notes:
 * - Profiles are upserted per (student_id, teacher_id), so only the LATEST
 *   profile is fully accurate. Earlier profiles in the history will only have
 *   data if a snapshot was preserved (currently not — see deferred work).
 *   For now we still return the latest profile linked to the most recent
 *   completed attempt, plus the `evolution_summary` text generated by the edge
 *   function which embeds the historical comparison.
 */
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { StudentProfile } from '@/hooks/dslm/useStudentProfile';

export interface WelcomeAttempt {
  test_id: string;
  attempt_number: number;
  previous_attempt_id: string | null;
  status: string;
  completed_at: string | null;
  created_at: string | null;
  total_questions: number | null;
  answered_count: number | null;
  score_percentage: number | null;
  profile: StudentProfile | null; // populated only for the latest completed attempt
}

interface UseWelcomeTestHistoryProps {
  studentId: string;
  teacherId: string;
}

export const useWelcomeTestHistory = ({ studentId, teacherId }: UseWelcomeTestHistoryProps) => {
  return useQuery({
    queryKey: ['welcome-test-history', studentId, teacherId],
    queryFn: async (): Promise<WelcomeAttempt[]> => {
      const { data: tests, error: testsErr } = await supabase
        .from('student_tests')
        .select('id, attempt_number, previous_attempt_id, status, completed_at, created_at, total_questions, answered_count, score_percentage')
        .eq('student_id', studentId)
        .eq('teacher_id', teacherId)
        .eq('test_type', 'welcome')
        .is('deleted_at', null)
        .order('attempt_number', { ascending: true });

      if (testsErr) throw testsErr;
      if (!tests || tests.length === 0) return [];

      // Latest profile (only one row per student/teacher)
      const { data: profile } = await supabase
        .from('student_learning_profiles')
        .select('*')
        .eq('student_id', studentId)
        .eq('teacher_id', teacherId)
        .maybeSingle();

      const latestCompletedId = [...tests]
        .reverse()
        .find(t => t.status === 'completed' || t.status === 'reviewed')?.id;

      return tests.map(t => ({
        test_id: t.id,
        attempt_number: t.attempt_number ?? 1,
        previous_attempt_id: t.previous_attempt_id ?? null,
        status: t.status,
        completed_at: t.completed_at,
        created_at: t.created_at,
        total_questions: t.total_questions,
        answered_count: t.answered_count,
        score_percentage: t.score_percentage as number | null,
        profile: t.id === latestCompletedId ? (profile as StudentProfile | null) : null,
      }));
    },
    enabled: !!studentId && !!teacherId,
    staleTime: 60 * 1000,
  });
};