// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use this to verify the Edooqoo MCP server is reachable.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list_exercise_types.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
import {
  NO_MEDIA_EXERCISE_IDS,
  PICTURE_EXERCISE_IDS,
  AUDIO_EXERCISE_IDS
} from "npm:@/lib/exerciseTaxonomy";
var list_exercise_types_default = defineTool2({
  name: "list_exercise_types",
  title: "List Edooqoo exercise types",
  description: "Return the catalog of ESL exercise types Edooqoo can generate, grouped by media requirement (no-media, picture-based, audio-based). Useful for lesson-plan assistants that need to know which exercise formats Edooqoo supports.",
  inputSchema: {
    media: z2.enum(["all", "no_media", "picture", "audio"]).default("all").describe("Filter by media requirement. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ media }) => {
    const groups = {
      no_media: [...NO_MEDIA_EXERCISE_IDS],
      picture: [...PICTURE_EXERCISE_IDS],
      audio: [...AUDIO_EXERCISE_IDS]
    };
    const payload = media === "all" ? groups : { [media]: groups[media] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list_topics.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
import pseoMatrix from "npm:@/data/pseoMatrix.json";
var topics = pseoMatrix.topics ?? [];
var list_topics_default = defineTool3({
  name: "list_topics",
  title: "List Edooqoo ESL topics",
  description: "Return the Edooqoo ESL topic catalog (grammar, vocabulary, skills). Optionally filter by category or search substring. Useful for suggesting adult 1:1 lesson focus areas.",
  inputSchema: {
    category: z3.string().optional().describe("Filter by category (e.g. grammar, vocabulary, skills)."),
    query: z3.string().optional().describe("Case-insensitive substring match on slug or label."),
    limit: z3.number().int().min(1).max(60).default(40)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, query, limit }) => {
    const q = query?.toLowerCase() ?? "";
    const filtered = topics.filter((t) => category ? t.category === category : true).filter(
      (t) => q ? t.slug.toLowerCase().includes(q) || t.label.toLowerCase().includes(q) : true
    ).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { topics: filtered, count: filtered.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "edooqoo-mcp",
  title: "Edooqoo \u2014 1-Minute Prep for English Tutors",
  version: "0.1.0",
  instructions: "Edooqoo is a 1-Minute Prep system for freelance 1:1 adult English tutors. Use `list_exercise_types` to see which worksheet formats Edooqoo can generate, `list_topics` to browse the ESL topic catalog, and `echo` to verify connectivity. This MCP server only exposes public catalog data; teacher- and student-scoped tools are intentionally not exposed until authenticated MCP is wired up.",
  tools: [echo_default, list_exercise_types_default, list_topics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
