import { describe, expect, it } from 'vitest';
import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Em dashes (U+2014, &mdash;) read as AI-generated English, so they are banned in
// user-facing and generated text. Regexes and normalizers must use the "—" escape.
const EM_DASH = String.fromCharCode(0x2014);

const EXCLUDED = [
  /^supabase\/migrations\//, // already applied, immutable
  /^supabase\/functions\/generateWorksheet\//, // protected engine
  /^supabase\/functions\/format-worksheet-prompt\//, // protected engine
  /^src\/data\/welcomeTestTranslations\.ts$/, // non-English locales use the dash natively
  /^(mem|\.lovable)\//, // internal notes and history
  /^docs\/(?!seo\/)/, // internal docs (docs/seo holds generated site data and stays checked)
  /^docs\/seo\/runs\//, // historical measurement data
  /^roadmap\.md$/,
  /(^|\/)llms(-full)?\.txt$/, // generated by scripts/seo/generate-ai-resources.mjs
  /^supabase\/functions\/mcp\/index\.ts$/, // generated by @lovable.dev/mcp-js
  /\.bak$/,
  /\.(png|jpe?g|gif|webp|ico|woff2?|ttf|pdf|mp3|mp4)$/,
  /^(package-lock\.json|bun\.lock)$/,
  /^src\/lib\/__tests__\/noEmDash\.test\.ts$/,
  /^AGENTS\.md$/,
];

describe('no em dashes in user-facing text', () => {
  it('has no U+2014 or &mdash; in tracked source, public pages or Edge Functions', () => {
    const root = resolve(__dirname, '../../..');
    const files = execSync('git ls-files', { cwd: root, encoding: 'utf8', maxBuffer: 1 << 28 })
      .split('\n')
      .filter(Boolean)
      .filter((f) => !EXCLUDED.some((re) => re.test(f)));
    const offenders: string[] = [];
    for (const f of files) {
      let text: string;
      try {
        text = readFileSync(resolve(root, f), 'utf8');
      } catch {
        continue;
      }
      if (text.includes(EM_DASH) || text.includes('&mdash;')) offenders.push(f);
    }
    expect(offenders).toEqual([]);
  });
});
